ARG ARCH
ARG VERSION
ARG VARIANT

FROM 529299063686.dkr.ecr.eu-central-1.amazonaws.com/snow-leopard/modbus-connector:${VERSION}

ARG ARCH
ARG VERSION
ARG VARIANT

RUN [ ! -z "${ARCH}" ]
RUN [ ! -z "${VERSION}" ]
